"faster_less_accurate_charting" : False
"fairshare_enabled" : False
"visualise_each_task" : False
"target_utilisation" : 120
"workload_filename" : "/gpfs/thirdparty/auk-cfms-r/home/aburkimsher/GridSim/gridsim/workload6.wld"
"platform_filename" : "/gpfs/thirdparty/auk-cfms-r/home/aburkimsher/GridSim/gridsim/platform_3_3000_1_1000.txt"
"print_metrics_by_job" : False
"debugging_on" : False
"schedule_output_filename" : "depprob4.csv"
"faster_charting_factor" : 1000000
"cluster_orderer" : "projected_slr"
"cumulative_completion_base" : 10000000000
"simulation_max_time" : 10000000000000000000
"use_supplied_submit_times" : False
"fairshare_tree_filename" : "/gpfs/thirdparty/auk-cfms-r/home/aburkimsher/GridSim/gridsim/fairshares2.txt"
"max_job_count" : 20000
"staggered_release" : True
"print_global_metrics" : True
"cluster_allocator" : "first_free"
"output_schedule_to_file" : False
"visualisation_enabled" : False
"router_orderer" : "fifo_job"
"router_allocator" : "load_balancing_allocator"
"networking_enabled" : True
"network_delay_level_power" : 2
"communication_to_computation_ratio" : 0.2
"proportion_of_kind2" : 0.2