"faster_less_accurate_charting" : False
"fairshare_enabled" : False
"visualise_each_task" : False
"target_utilisation" : 120
"workload_filename" : "/Users/andy/Documents/Work/workloads_march_12/synthetics/power_jobs_chains_blocks/jobs_chains_blocks_10.txt"
"platform_filename" : "/Users/andy/Documents/Work/gridsimxcode/GridSim/gridsim/platform1000cores.plat"
"print_metrics_by_job" : False
"debugging_on" : False
"schedule_output_filename" : "depprob4.csv"
"faster_charting_factor" : 1000000
"cluster_orderer" : "pslr_sf"
"cumulative_completion_base" : 10000000000
"simulation_max_time" : 10000000000000000
"use_supplied_submit_times" : False
"fairshare_tree_filename" : "/Users/andy/Documents/Work/gridsimxcode/GridSim/gridsim/fairshares2.txt"
"max_job_count" : 1000000
"staggered_release" : True
"print_global_metrics" : True
"cluster_allocator" : "first_free"
"output_schedule_to_file" : False
"visualisation_enabled" : False
"router_orderer" : "fifo_job"
"router_allocator" : "first_free"
"networking_enabled" : False
"network_delay_level_power" : 2
"communication_to_computation_ratio" : 0.2
"proportion_of_kind2" : 0.0
"exec_time_estimate_kind" : "exact"
"exec_time_estimate_value" : 10000000
"human_readable_metrics" : True
"metrics_out_formats" : ["text_human"]
"value_enabled" : False
"curves_filename" : "/Users/andy/Documents/Work/gridsimxcode/GridSim/gridsim/big_curves_file.txt"
"job_exec_timeout_factor" : 5000000
"random_seed" : 123456
"print_schedule" : True